name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
        wait-timeout-minutes: 10
