name: "C/I"
on:
  push:
    branches: [ main ]
jobs:
  ci:
    name: "C/I"
    runs-on: ubuntu-latest
    steps:
      - name: "fetch"
        uses: actions/checkout@v3
      
      - name: "compile"
        run: |
          mkdir ~/.code && unzip -d ~/.code code.zip
          cp run.sh ~/.code && chmod +x ~/.code/run.sh
          cd ~/.code && ./run.sh

